### ISSUE TITLE
Option to log the real IP if behind a reverse proxy?

### ISSUE THREAD

**Issue by chmac** [monicahq/docker#108]
I'm running a monica docker container behind a separate SSL proxy. I've set the proxy's IP in the `APP_TRUSTED_PROXIES` variable. When I look at my logs in docker, I get the IP of the proxy showing up and not my client's actual IP. Is there any way to fix that by setting some other environment variable or otherwise?

**Comment by asbiin** [comment]
You need to setup a proper reverse proxy.
The `APP_TRUSTED_PROXIES` setting is on the application side, and not on the docker container level.

**Comment by chmac** [comment]
My reverse proxy works fine. Apache can be configured to log either the connecting IP or the IP provided by the reverse proxy. Currently it's logging the connecting IP, which is likely not so useful in a docker context.

You closed the ticket as completed, does that mean you're not open to adding this option?

With the current setup the logs are not so useful as all requests have the same IP...
