### ISSUE TITLE
Accidentially deleted Monica Container, how to re-connect to existing Mysql Container?

### ISSUE THREAD

**Issue by mptpro** [monicahq/docker#123]
I accidentally deleted my Monica container, but the Mysql container is still there with my data.

I created a new Monica container, but I don't know how to link/connect it to my existing mysql container.

I can create a new set of containers  using the command in the instructions: 

```
mysqlCid="$(docker run -d \
 -e MYSQL_RANDOM_ROOT_PASSWORD=true \
 -e MYSQL_DATABASE=monica \
 -e MYSQL_USER=homestead \
 -e MYSQL_PASSWORD=secret \
 "mysql:5.7")"
docker run -d \
 --link "$mysqlCid":mysql \
 -e DB_HOST=mysql \
 -p 8080:80 \
 monica
```

But this creates a new mysql databse.

I've spent hours searching, and I appreicated any help.

**Comment by asbiin** [comment]
Sorry @mptpro 
When this happen, you need to get the id of the running mysql with `docker ps`, and use this id in place of the `$mysqlCid`.
