### ISSUE TITLE
Docker MySQL container updated and Monica data is gone.

### ISSUE THREAD

**Issue by mptpro** [monicahq/docker#126]
I updated my MySQL container running MySQL 5.7, and now when I go to Monica I get the "create new account" screen.

I'm not sure what to do at this point to get it working again. Any help is appreciated.

**Comment by asbiin** [comment]
Sorry for your data lost @mptpro docker is cruel sometimes ...
Like @rursache advice, you need to store mysql data on a persistent storage.
