### ISSUE TITLE
Need relative links, as opposed to absolute.

### ISSUE THREAD

**Issue by phattlmann** [monicahq/docker#130]
I've been having a hell of a time getting this to work with docker and having it exposed to the outside work behind a reverse proxy. While it loads, it seems the CSS isn't loading as nicely.

Digging around, it seems like the CSS style sheets are linked with a hard link as such:
`<link rel="stylesheet" href="http://monica.xxxxx.com/css/app-ltr.css?id=xxxxxxxxxxxxxxxxxx">`

When they should really be something like: 
`<link rel="stylesheet" href="https://monica.xxxxx.com/css/app-ltr.css?id=xxxxxxxxxxxxxxxxxx">`

This makes me believe the code was written without using relative links, and more-so with hard links, specifically http as opposed to allowing for a check for https. Am I off here, or can this be looked into? Thanks!

**Comment by asbiin** [comment]
That means your reverse proxy isn't working 100%. You can also set `APP_TRUSTED_PROXIES` with ip addresses of your proxy, or with `*`.
