### ISSUE TITLE
2016_09_10_164406_create_jobs_table FAIL on the first start

### ISSUE THREAD

**Issue by pkirk** [monicahq/docker#131]
I'm trying to install Monica on my QNAP NAS using the "latest" docker version, but seems to be a problem with my MariaDB (the default and latest "10" version from QNAP, "10.5.8-MariaDB-log - MariaDB Server".

`In Connection.php line 760:

  [Illuminate\Database\QueryException (42000)]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes (SQL: alter table `monicajobs` add in
  dex `monicajobs_queue_reserved_at_index`(`queue`, `reserved_at`))

Exception trace:
  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
 Illuminate\Database\Connection->runQueryCallback() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:720
 Illuminate\Database\Connection->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:546
 Illuminate\Database\Connection->statement() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:109
 Illuminate\Database\Schema\Blueprint->build() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:439
 Illuminate\Database\Schema\Builder->build() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:285
 Illuminate\Database\Schema\Builder->create() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:338
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/html/database/migrations/2016_09_10_164406_create_jobs_table.php:25
 CreateJobsTable->up() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:481
 Illuminate\Database\Migrations\Migrator->runMethod() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:399
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:408
 Illuminate\Database\Migrations\Migrator->runMigration() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:209
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php:36
 Illuminate\Console\View\Components\Task->render() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:738
 Illuminate\Database\Migrations\Migrator->write() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:209
 Illuminate\Database\Migrations\Migrator->runUp() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:174
 Illuminate\Database\Migrations\Migrator->runPending() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:117
 Illuminate\Database\Migrations\Migrator->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:90
 Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:615
 Illuminate\Database\Migrations\Migrator->usingConnection() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:102
 Illuminate\Database\Console\Migrations\MigrateCommand->handle() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
 Illuminate\Container\Util::unwrapIfClosure() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:663
 Illuminate\Container\Container->call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:152
 Illuminate\Console\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:102
 Illuminate\Console\Application->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:155
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/artisan:37`

And Laravel documentation seems to be clear on that on how to fix:
https://laravel.com/docs/9.x/migrations#index-lengths-mysql-mariadb

Can you please check and advice?

**Comment by asbiin** [comment]
I can't reproduce that
