### ISSUE TITLE
Issue with documentation!

### ISSUE THREAD

**Issue by Mrs-Feathers** [monicahq/docker#132]
Hello! i am looking for the page at https://github.com/monicahq/docker/blob/main/docs/installation/mail.md which doesn't exist. all i need to know is for the environmental variables i can set in docker compose for monica for MAIL_* to set up a mail server, otherwise it's impossible to use this as it requires mail to invite and other things.

in short, i'm looking for a simple list of what different MAIL_* variables there are so i can set it up myself.

**Comment by rahilarious** [comment]
Hey. It think it moved to monicahq/monica repo but anyway look at [this example](https://github.com/monicahq/docker/tree/main/.examples/raspberrypi) implementation to make it work perfectly. 

To get emails working, one need to set MAIL_* env variables and run a cron job too.

**Comment by asbiin** [comment]
@Mrs-Feathers You are looking for this documentation: https://github.com/monicahq/monica/blob/4.x/docs/installation/mail.md
