### ISSUE TITLE
Forced https

### ISSUE THREAD

**Issue by akrly** [monicahq/docker#135]
Hi,

Great app first of all! I've got some experience, but am not professionally trained. 

I tried to self-host on a raspberry pi using the docker-compose file. Everything looks good in the docker logs, but I get a secure connection error when I try to access the UI.

![image](https://github.com/monicahq/docker/assets/40865147/8a143634-8c5d-4426-b711-d2c84bac7b9b)

This is what I get when I manually change to http from https. However, all the links on this page will direct to a secure site.

![image](https://github.com/monicahq/docker/assets/40865147/003787a3-69d3-4c41-8c5a-f4194310850c)

---

I used the [provided files](https://github.com/monicahq/docker/tree/main/.examples/raspberrypi) to setup the containers. Didn't change anything apart from the db_username so they match. I tried to access the site locally.

Any help is much appreciated. I hope I gave enough info to describe my problem.

**Comment by remus-selea** [comment]
I had a similar issue but fixed it by adding the `APP_ENV=production` environment variable to monica, [as documented in the readme](https://github.com/monicahq/docker#make-monica-available-from-the-internet). The stylesheets were then available over HTTPS.

**Comment by asbiin** [comment]
That means your reverse proxy isn't working 100%. You can also set `APP_TRUSTED_PROXIES` environment variable with the ip addresses of your proxy / webserver, or with `*`.
