### ISSUE TITLE
Lost APP_KEY

### ISSUE THREAD

**Issue by garfieldairlines** [monicahq/docker#144]
Hello,
I migrated the docker container and to be honest I forgot that the APPP_KEY setting was a thing. So I can't connect to Monica.

Is there a way to hard reset the user password ? I am the admin of MariaDB after all…

**Comment by NewtTheWolf** [comment]
Hawoof @garfieldairlines,

In Theorie yes

in my case i would firstly setup a new Monica with the new Secret
After that i would create a new user, go to the Database->Table:users and then copy the password
Then i would start the Old Monica with the new Secret and go again to Database->Table:users and then replace the old password string with the new Password String ^^

And then in theory it should work

i'm right @djaiss ?

**Comment by djaiss** [comment]
So in theory, this is how you should do:

- generate a new APP_KEY in your project with `php artisan key:generate` in the console
- get the encrypted password by invoking Tinker (`php artisan tinker`) and typing `Hash::make('YOUR_NEW_PASSWORD')` as shown below
- update the password of your user in the database manually.

This will update the system with the new password.

<img width="592" alt="image" src="https://github.com/monicahq/docker/assets/61099/e480bf7e-b1fd-4e37-91a8-01a825e16856">

**Comment by asbiin** [comment]
You can reset the password with the reset password form.
