### ISSUE TITLE
Define Database Port

### ISSUE THREAD

**Issue by Wdavery** [monicahq/docker#36]
Is it possible to define what port the db is to be accessed at. I'd like to run mariadb on a port besides 3306

**Comment by asbiin** [comment]
Please read the documentation https://github.com/monicahq/docker/blob/master/README.md
See here the example off `.env` file: https://github.com/monicahq/monica/blob/master/.env.example
In your case, you'll have to set the `DB_PORT` environment variable.

**Comment by Wdavery** [comment]
Thank you for the link, apologies for the seemingly unnecessary issue.
I dug through many pages of documentation and couldn't find anything. Also saw conflicting information in a few places.

Not the right place to ask likely, but are you open to contributions for cleaning up the docs?

**Comment by Wdavery** [comment]
In fact after a closer look, that documentation you linked does not have the required information at all. 
The .env.example is not in this repo, nor is it linked to from the documentation here.
