### ISSUE TITLE
Any plans for an "all-in-one" container?

### ISSUE THREAD

**Issue by zvr** [monicahq/docker#40]
Is there any plans for a single container that can run Monica without any other dependencies?

Reading the documentation, it seems that it could be easily constructed, simply by adding mysql in one of the existing containers.

**Comment by asbiin** [comment]
Adding mysql directly in the container does not follow docker's recommendations.
See examples of docker-compose in the [example](https://github.com/monicahq/docker/tree/master/.examples) section.

You can always create your own container with mysql server inside. But this will not be part of the official image.
