### ISSUE TITLE
Waiting for database to settle...  MySQL Connection Error: (1045) Access denied for user

### ISSUE THREAD

**Issue by MichaelData** [monicahq/docker#73]
Hello I'm currently trying to get monica CRM to run using docker but every time I do I get this error

```
Waiting for database to settle...

Fatal error: Uncaught Error: mysqli object is already closed in Standard input code:40

Stack trace:

#0 Standard input code(40): mysqli->close()


}

  thrown in Standard input code on line 40

Waiting for database to settle...

MySQL Connection Error: (1045) Access denied for user 'homestead'@'ipaddress' (using password: YES)


Unable to contact your databaseAPP_KEY already set


Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'homestead'@'ipaddress' (using password: YES) in Standard input code on line 34


MySQL Connection Error: (1045) Access denied for user 'homestead'@'ipaddress' (using password: YES)


Waiting for database to settle...
```

where it says ipaddress I removed mine but it was saying the correct one.

this keeps happening not matter what I do

**Comment by Paduber** [comment]
Similar issue here

`Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 34
Waiting for database to settle...
MySQL Connection Error: (2002) Connection refused

Waiting for database to settle...
MySQL Connection Error: (2002) Connection refused
`
I'm pretty sure db is ok, because it was working before I decided to update monica image

**Comment by mfabache** [comment]
I have the same issue now for months as well (granted, I've given up as well), have you got this resolved?

**Comment by jinyeow** [comment]
```mysql
APP_KEY already set
Database ready.
2022-01-24 18:38:36 | MySQL "CREATE DATABASE" Error: Access denied for user 'homestead'@'%' to database 'monica'
```

I'm getting the above. Any ideas?

**Comment by jcm4atx** [comment]
Same here. I don't understand the issue. I have other services running with nearly identical docker-compose.yml files, just calling the other application instead of monica and they work just fine.

**Comment by FPMilan** [comment]
Same

**Comment by mitchplze** [comment]
Same problem on RPi, using the example file

**Comment by mitchplze** [comment]
Adding the following lines to my .env file fixed this issue.

_Under the existing "DB_HOST" line:_ 

```
DB_DATABASE=monica
DB_USERNAME=homestead
DB_PASSWORD=sameValueYouSpecifiedInDockerCompose
```

**Comment by FPMilan** [comment]
Using docker compose with the depend on statement on the frontend container to wait for the DB to finish deployment worked for me

**Comment by Aethelraed** [comment]
I faced the same problem. Deleting the volumes from an earlier installation attempt solved it for me.
