### ISSUE TITLE
Scheduled emails not sending, Test is OK (Docker Supervised)

### ISSUE THREAD

**Issue by mikekay1** [monicahq/docker#74]
Trying to get email working I know my configuration is correct.

From other tickets I have drawn that I need to copy some files from somewhere to somewhere else?

I tried send:reminders and no email is sent either, even though there are things for that month.

**Docker-Compose**
`version: "3.4"

services:
  app:
    container_name: prod_monica_monica
    image: monica:apache
    depends_on:
      - db
    ports:
      - 8003:80
    environment:
      - DB_HOST=db
      - DB_USERNAME=@@@@
      - DB_PASSWORD=@@@@
      - MAIL_MAILER=smtp
      - MAIL_HOST=192.168.1.xxx
      - MAIL_PORT=25
      - MAIL_ENCRYPTION=
      - MAIL_FROM_ADDRESS=monica_reminder@foobar.com
      - MAIL_FROM_NAME="Monica Reminder"
    volumes:
      - ./var/www/html/storage:/var/www/html/storage
    restart: always

  db:
    container_name: prod_monica_db
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=@@@@@
      - MYSQL_PASSWORD=@@@@@
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql`

**Comment by asbiin** [comment]
I don't think you can use `MAIL_HOST=192.168.1.xxx` as your mail server.
Laravel `smtp` uses transactional emails. You'll need something like `mailgun`, `postmark`, or `SES`.
