### ISSUE TITLE
unable to use 'POST' method through API

### ISSUE THREAD

**Issue by mrderiuzz** [monicahq/docker#79]
when using 'latest' image I seem not to be able to use POST requests through API. I tested GET and PUT and it all works as expected. However, whenever I run a request with POST, for example to create activity or contact field, I get:

The server returned a "405 Method Not Allowed"

this is also happening on the live instance on https://app.monicahq.com/

this has not been happening for me on Heroku deployment but I assume it used different version of the app. 

Can you point me in the direction how do I configure my docker image to accept POST?

**Comment by asbiin** [comment]
Hi. I'll have to close this issue which doesn't have enough information to answer it.
Please try to get help on generic forums like stackoverflow.
