### ISSUE TITLE
Monica HQ MySQL "mysqlCid is not recognized as an internal or external command" error

### ISSUE THREAD

**Issue by fatpanguin** [monicahq/docker#94]
I got to the step in setting up Monica HQ where I need to get the MySQL environment running (Connect to a mysql database) but when I enter 

> _mysqlCid="$(docker run -d \
>  -e MYSQL_RANDOM_ROOT_PASSWORD=true \
>  -e MYSQL_DATABASE=monica \
>  -e MYSQL_USER=homestead \
>  -e MYSQL_PASSWORD=secret \
>  "mysql:5.7")"_

into CMD I get this error: "mysqlCid is not recognized as an internal or external command"

**Comment by asbiin** [comment]
This command is not for `cmd`, but for a linux shell, like `bash`
