### ISSUE TITLE
Cant access monica server

### ISSUE THREAD

**Issue by JunkyardCat** [monicahq/docker#97]
hi 
i have followed every instruction on the monica docker page and have successfully installed monica/mysql but when i access the monica server using localhost:8080 it just gives error. the only thing i change is the docker command
from
"docker run --name some-monica -d -p 8080:80 monica" to "docker run --name panda-monica -d -p 8080:80 monica"

![monica access error](https://user-images.githubusercontent.com/22941307/149702992-cd64d2a8-190f-4146-916e-7953c9ce4c26.png)

i am using debian bullseye
latest monica at this time
latest docker and docker-compose as of this time

**Comment by ragelfundionctrumnar** [comment]
Possibly a c&p issue with APP_KEY?
Make sure to include the full output of "echo -n 'base64:'; openssl rand -base64 32"

It should start with "base64:" and end with "="

**Comment by asbiin** [comment]
thank you @ragelfundionctrumnar for this solution
